# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trainerSettingsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
import Trainer


class Ui_Dialog(object):
    def setupUi(self, Dialog, nPositives, w, h, answer):
        """

        :rtype: object
        """
        self.minStages = 1
        self.minHitRate = 90
        self.minNumSamples = 2

        self.maxStages = 50
        self.maxHitRate = 99
        self.maxNumSamples = nPositives

        self.currentStages = self.minStages
        self.currentHitRate = self.minHitRate
        self.currentNumSamples = self.minNumSamples

        self.w = w
        self.h = h
        self.answer = answer



        Dialog.setObjectName("Cascade trainer settings")
        Dialog.setStyleSheet("background-color: rgb(57, 62, 65);")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 73, 91, 20))
        self.label_2.setStyleSheet("font: 11pt \"Zwizz\";\n"
"color: rgb(215, 232, 186);")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 113, 101, 17))
        self.label_4.setStyleSheet("font: 11pt \"Zwizz\";\n"
"color: rgb(215, 232, 186);")
        self.label_4.setObjectName("label_4")

        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(350, 220, 291, 61))
        self.label_7.setStyleSheet("font: 9pt \"Zwizz\";\n"
                                   "color: rgb(119, 118, 123);\n"
                                   "")
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")

        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(457, 110, 89, 25))
        self.pushButton.setStyleSheet("color: rgb(255, 166, 48);")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(280, 147, 40, 25))
        self.lineEdit_2.setStyleSheet("color: rgb(255, 166, 48);\n"
"font: 11pt \"Zwizz\";")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(280, 187, 40, 25))
        self.lineEdit_3.setStyleSheet("color: rgb(255, 166, 48);\n"
"font: 11pt \"Zwizz\";")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 20, 391, 21))
        self.label.setStyleSheet("font: 15pt \"Neon\";\n"
"color: rgb(255, 166, 48);")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(280, 110, 40, 25))
        self.lineEdit.setStyleSheet("color: rgb(255, 166, 48);\n"
"font: 11pt \"Zwizz\";")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(102, 240, 120, 25))
        self.pushButton_4.setStyleSheet("color: rgb(255, 166, 48);\n"
"font: 11pt \"Zwizz\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(457, 150, 89, 25))
        self.pushButton_2.setStyleSheet("color: rgb(255, 166, 48);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(325, 60, 20, 221))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(457, 190, 89, 25))
        self.pushButton_3.setStyleSheet("color: rgb(255, 166, 48);\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 190, 101, 17))
        self.label_6.setStyleSheet("font: 11pt \"Zwizz\";\n"
"color: rgb(215, 232, 186);")
        self.label_6.setObjectName("label_6")
        self.horizontalSlider = QtWidgets.QSlider(Dialog)
        self.horizontalSlider.setGeometry(QtCore.QRect(120, 113, 151, 20))
        self.horizontalSlider.setStyleSheet("")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(470, 70, 67, 17))
        self.label_3.setStyleSheet("font: 11pt \"Zwizz\";\n"
"color: rgb(215, 232, 186);")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 150, 101, 17))
        self.label_5.setStyleSheet("font: 11pt \"Zwizz\";\n"
"color: rgb(215, 232, 186);")
        self.label_5.setObjectName("label_5")


        self.horizontalSlider_2 = QtWidgets.QSlider(Dialog)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(120, 190, 151, 20))
        self.horizontalSlider_2.setStyleSheet("")
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider_4 = QtWidgets.QSlider(Dialog)
        self.horizontalSlider_4.setGeometry(QtCore.QRect(120, 150, 151, 20))
        self.horizontalSlider_4.setStyleSheet("")
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(120, 70, 86, 25))
        self.comboBox.setStyleSheet("color: rgb(255, 166, 48);")
        self.comboBox.setObjectName("comboBox")

        self.pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_4.setFocusPolicy(QtCore.Qt.NoFocus)

        self.horizontalSlider.setMinimum(self.minStages)
        self.horizontalSlider_4.setMinimum(self.minHitRate)
        self.horizontalSlider_2.setMinimum(self.minNumSamples)

        self.horizontalSlider.setMaximum(self.maxStages)
        self.horizontalSlider_4.setMaximum(self.maxHitRate)
        self.horizontalSlider_2.setMaximum(self.maxNumSamples)


        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        self.dialog = Dialog
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "FeatureType:"))
        self.label_4.setText(_translate("Dialog", "N of stages"))
        self.pushButton.setText(_translate("Dialog", "Good"))
        self.label.setText(_translate("Dialog", "Select trainer properties"))
        self.pushButton_4.setText(_translate("Dialog", "Start!"))
        self.pushButton_2.setText(_translate("Dialog", "Better"))
        self.pushButton_3.setText(_translate("Dialog", "Best"))
        self.label_6.setText(_translate("Dialog", "N of samples"))
        self.label_3.setText(_translate("Dialog", "Presets"))
        self.label_5.setText(_translate("Dialog", "MinHitRate"))
        self.label_7.setText(_translate("Dialog", "Note: This is purely an indication, results will vary depending on settings and on quality of given samples"))

        self.comboBox.addItems(["HAAR", "LBP"])
        self.pushButton.clicked.connect(self.setGoodSettings)
        self.pushButton_2.clicked.connect(self.setBetterSettings)
        self.pushButton_3.clicked.connect(self.setBestSettings)
        self.pushButton_4.clicked.connect(self.start)

        self.horizontalSlider.valueChanged.connect(self.setSliderNStages)
        self.horizontalSlider_4.valueChanged.connect(self.setSliderMinHitRate)
        self.horizontalSlider_2.valueChanged.connect(self.setSliderNumSamples)

        self.lineEdit.returnPressed.connect(self.setLineNStages)
        self.lineEdit_2.returnPressed.connect(self.setLineMinHitRate)
        self.lineEdit_3.returnPressed.connect(self.setLineNumSamples)
        self.horizontalSlider.setFocus()
        self.setGoodSettings()





    def setGoodSettings(self):
        self.comboBox.setCurrentIndex(1)
        self.horizontalSlider.setValue(10)
        self.horizontalSlider_4.setValue(90)
        self.lineEdit_2.setText("90")
        self.horizontalSlider_2.setValue(self.maxNumSamples/4)



    def setBetterSettings(self):
        self.comboBox.setCurrentIndex(0)
        self.horizontalSlider.setValue(25)
        self.horizontalSlider_4.setValue(95)
        self.horizontalSlider_2.setValue(self.maxNumSamples / 2)

    def setBestSettings(self):
        self.comboBox.setCurrentIndex(0)
        self.horizontalSlider.setValue(50)
        self.horizontalSlider_4.setValue(99)
        self.horizontalSlider_2.setValue(self.maxNumSamples)

    def setSliderNStages(self):
        self.lineEdit.setText(str(self.horizontalSlider.value()))

    def setSliderMinHitRate(self):
        self.lineEdit_2.setText(str(self.horizontalSlider_4.value()))

    def setSliderNumSamples(self):
        self.lineEdit_3.setText(str(self.horizontalSlider_2.value()))

    def setLineNStages(self):
        self.horizontalSlider.setValue(int(self.lineEdit.text()))

    def setLineMinHitRate(self):
        self.horizontalSlider_4.setValue(int(self.lineEdit_2.text()))

    def setLineNumSamples(self):
        self.horizontalSlider_2.setValue(int(self.lineEdit_3.text()))

    def start(self):
        self.dialog.accept()
        Trainer.trainCascade(self.comboBox.currentText(), self.horizontalSlider.value(), self.horizontalSlider_4.value(), self.horizontalSlider_2.value(), self.w, self.h, self.answer)